# Generated by Django 3.0.5 on 2020-04-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Mobile_No', models.CharField(max_length=20)),
                ('Auth_Token', models.CharField(max_length=200)),
                ('Is_Deleted', models.BooleanField(default=True)),
            ],
        ),
    ]
