# Generated by Django 3.0.5 on 2020-04-09 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapi', '0002_booking_doctors_hospitals_hospitalstaff_sessionid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionId',
            new_name='Session',
        ),
    ]
