# Generated by Django 3.0.5 on 2020-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docapi', '0003_auto_20200410_0233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=25)),
                ('Name', models.CharField(max_length=25)),
            ],
        ),
    ]
