# Generated by Django 3.0.5 on 2020-04-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docapi', '0004_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='Id',
            new_name='Test_Id',
        ),
    ]
